
<?php

$popupModuled = $this->getConfig('enable');
$popupEnabled = $this->getConfig('enable_popup');
$popupTitle = $this->getConfig('popup_title');
$popupText = $this->getConfig('popup_text');

$asset_repository = $this->assetRepository;

$bootstrapCssAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::modal_and_btn_bootstrap.css');
$bootstrapJsAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::modal_bootstrap.js');
$modalControllerAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::modal_controller.js');
$withoutPopupAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::without_popup.js');

$bootstrapCssUrl = $bootstrapCssAsset->getUrl();
$bootstrapJssUrl = $bootstrapJsAsset->getUrl();
$modalControllerUrl = $modalControllerAsset->getUrl();
$withoutPopupUrl = $withoutPopupAsset->getUrl();

?>

<?php if($popupModuled==1 && $popupEnabled==1): ?>
	
	<script src="<?php echo $bootstrapJssUrl; ?>"></script>
	
	<link rel="stylesheet" href="<?php echo $bootstrapCssUrl; ?>">

	<script>
	    require(
	        [
	            'jquery'
	        ],
	        function($) {

	        //Append Modal To Body

	        $("body").append('\
				  <!-- External Links Modal -->\
				  <div class="modal fade" id="externalLinksModal" role="dialog">\
				    <div class="modal-dialog">\
				      <!-- Modal content-->\
				      <div class="modal-content">\
				        <div class="modal-header">\
				          <button type="button" class="close" data-dismiss="modal">&times;</button>\
				          <h4 class="modal-title"><?php echo $popupTitle; ?></h4>\
				        </div>\
				        <div class="modal-body">\
				          <p><?php echo $popupText; ?></p>\
				        </div>\
				        <div class="modal-footer">\
				        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close') ?></button>\
				          <button type="button" id="dacod-external-links-continue" class="btn btn-default"><?php echo __('Continue') ?></button>\
				        </div>\
				      </div>\
				    </div>\
				  </div>');  
	        }
	    );
	</script>
	<script src="<?php echo $modalControllerUrl; ?>"></script>


<?php elseif($popupModuled==1 && $popupEnabled==0): ?>

	<script src="<?php echo $withoutPopupUrl; ?>"></script>

<?php endif; ?>