
<?php

$popupModuled = $this->getConfig('enable');
$popupEnabled = $this->getConfig('enable_popup');
$popupTitle = $this->getConfig('popup_title');
$popupText = $this->getConfig('popup_text');

$asset_repository = $this->assetRepository;

$bootstrapCssAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::modal_and_btn_bootstrap.css');
$bootstrapJsAsset = $asset_repository->createAsset('Dacod_ExternalLinksInNewTab::modal_bootstrap.js');

$bootstrapCssUrl = $bootstrapCssAsset->getUrl();
$bootstrapJssUrl = $bootstrapJsAsset->getUrl();


?>

<?php if($popupModuled==1 && $popupEnabled==1): ?>
	
	<script src="<?php echo $bootstrapJssUrl; ?>"></script>
	<link rel="stylesheet" href="<?php echo $bootstrapCssUrl; ?>">

	<script>
	    require(
	        [
	            'jquery'
	        ],
	        function($) {

		      var anchors = document.getElementsByTagName('a');

			  for (var i=0; i<anchors.length; i++){


			  if(!((anchors[i].href.indexOf(window.location.hostname) >= 0) || anchors[i].href=="#" || anchors[i].href=="javascript:void(0)")){

			   anchors[i].setAttribute('data-target', '#myModal');
			   anchors[i].setAttribute('data-toggle', 'modal');
			   

			  }
			    
			  }

	        $("body").append('\
				  <!-- Modal -->\
				  <div class="modal fade" id="myModal" role="dialog">\
				    <div class="modal-dialog">\
				      <!-- Modal content-->\
				      <div class="modal-content">\
				        <div class="modal-header">\
				          <button type="button" class="close" data-dismiss="modal">&times;</button>\
				          <h4 class="modal-title"><?php echo $popupTitle; ?></h4>\
				        </div>\
				        <div class="modal-body">\
				          <p><?php echo $popupText; ?></p>\
				        </div>\
				        <div class="modal-footer">\
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>\
				          <button type="button" id="dacod-external-links-continue" class="btn btn-default">Continue</button>\
				        </div>\
				      </div>\
				    </div>\
				  </div>');

	        	var dacodExternalLink = '';

	    
	           

	            $("a").on("click",function(event){


	            	if(!(($(this).attr('href').indexOf(window.location.hostname) >= 0) || $(this).attr('href')=="#" || $(this).attr('href')=="javascript:void(0)")){

		            	event.preventDefault();
		            	dacodExternalLink = $(this).attr('href');


	            	}       	

	            });

	            $("#dacod-external-links-continue").on("click",function(event){

	            	event.preventDefault();
	            	window.open(dacodExternalLink,'_blank');

	            });


	            
	        }
	    );
	</script>


<?php elseif($popupModuled==1 && $popupEnabled==0): ?>

	<script>

		window.onload = function(){

		  var anchors = document.getElementsByTagName('a');
		  for (var i=0; i<anchors.length; i++){

		    console.log(window.location.hostname);

		  if(!((anchors[i].href.indexOf(window.location.hostname) >= 0) || anchors[i].href=="#" || anchors[i].href=="javascript:void(0)")){

		   anchors[i].setAttribute('target', '_blank');

		  }
		    
		  }

		}

	</script>

<?php endif; ?>